export interface ViajesI {
    id:number,
    userConductor: string,
    idConductor: string,
    nombreConductor: string,
    edadConductor: string,
    imgConductor: string,
    emailConductor: string,
    generoConductor: string,
    fecha: string,
    hora: string,
    precio: string,
    pasajeros: string,
    origen: string,
    lngOrigen: string,
    latOrigen: string,
    regionDestino:string,
    comunaDestino:string,
    direccionDestino: string,
    lngDestino: string,
    latDestino: string
}
